NewSPCA/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewSPCA.Data;
using NewSPCA.Models;

namespace NewSPCA.Controllers
{
    [Authorize(Roles = "admin")]
    public class AnimalController : Controller
    {
        private readonly AnimalContext _context;

        public AnimalController(AnimalContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        // GET: Animal
        public async Task<IActionResult> Index()
        {
            var animalContext = _context.Animals.Include(a => a.Breed).Include(a => a.Site).Include(a => a.Species);
            return View(await animalContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Listing(int? speciesId)
        {
            var animals = _context.Animals
                .Include(i => i.Species)
                .Include(i => i.Breed)
                .Include(i => i.Site)
                .Where(a => !speciesId.HasValue || a.SpeciesID == speciesId);

            if(speciesId != null)
            {
                // we have a species ID
                var speciesType = _context.Species
                    .Where(s => s.SpeciesID == speciesId)
                    .SingleOrDefault();
                ViewData["SpeciesType"] = speciesType.Species_Name;
            }
            else
            {
                // no species ID / all species
                ViewData["SpeciesType"] = "All Specie";
            }

            return View(await animals.ToListAsync());
        }

        [AllowAnonymous]
        // GET: Animal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .Include(a => a.Breed)
                .Include(a => a.Site)
                .Include(a => a.Species)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animal/Create
        public IActionResult Create()
        {
            ViewData["BreedID"] = new SelectList(_context.Breeds, "BreedID", "Breed_Name");
            ViewData["SiteID"] = new SelectList(_context.Sites, "SiteID", "Site_Name");
            ViewData["SpeciesID"] = new SelectList(_context.Species, "SpeciesID", "Species_Name");
            return View();
        }

        // POST: Animal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Age,Gender,Size,Color,Intake_Date,Price,Declawed,Housebroken,Spayed_Neutered,SpeciesID,BreedID,SiteID")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedID"] = new SelectList(_context.Breeds, "BreedID", "Breed_Name", animal.BreedID);
            ViewData["SiteID"] = new SelectList(_context.Sites, "SiteID", "Site_Name", animal.SiteID);
            ViewData["SpeciesID"] = new SelectList(_context.Species, "SpeciesID", "Species_Name", animal.SpeciesID);
            return View(animal);
        }

        // GET: Animal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals.SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["BreedID"] = new SelectList(_context.Breeds, "BreedID", "Breed_Name", animal.BreedID);
            ViewData["SiteID"] = new SelectList(_context.Sites, "SiteID", "Site_Name", animal.SiteID);
            ViewData["SpeciesID"] = new SelectList(_context.Species, "SpeciesID", "Species_Name", animal.SpeciesID);
            return View(animal);
        }

        // POST: Animal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Age,Gender,Size,Color,Intake_Date,Price,Declawed,Housebroken,Spayed_Neutered,SpeciesID,BreedID,SiteID")] Animal animal)
        {
            if (id != animal.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedID"] = new SelectList(_context.Breeds, "BreedID", "Breed_Name", animal.BreedID);
            ViewData["SiteID"] = new SelectList(_context.Sites, "SiteID", "Site_Name", animal.SiteID);
            ViewData["SpeciesID"] = new SelectList(_context.Species, "SpeciesID", "Species_Name", animal.SpeciesID);
            return View(animal);
        }

        // GET: Animal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .Include(a => a.Breed)
                .Include(a => a.Site)
                .Include(a => a.Species)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animal = await _context.Animals.SingleOrDefaultAsync(m => m.ID == id);
            _context.Animals.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(int id)
        {
            return _context.Animals.Any(e => e.ID == id);
        }
    }
}

NewSPCA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SPCA</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @* brettdinelli:  adding reference to font-awesome css*@
        <link rel="stylesheet" href="~/lib/font-awesome/web-fonts-with-css/css/fontawesome-all.css" />
        <link href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
              asp-fallback-href="~/lib/font-awesome/web-fonts-with-css/css/fontawesome-all.min.css"
              asp-fallback-test-class="fa" asp-fallback-test-property="display"
              asp-fallback-test-value="inline-block" />
        <link href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SPCA</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @await Component.InvokeAsync("MenuComponent")
                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Animal" asp-action="Index">Animal Directory</a></li>
                    }
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>

    @*  brettdinelli:  rename main content and move footer outside *@
    <section class="margin">
        @RenderBody()
    </section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-3">
                    <div class="widget">
                        <h5>Contact Us</h5>
                        <address>
                            <strong>Greater Moncton SPCA</strong><br>
                            116 Greenock St.<br>
                            Moncton, NB  E1H 2J7
                        </address>
                        <p>
                            <i class="fas fa-phone"></i> (506) 857-8698<br>
                            <i class="fas fa-envelope"></i> info@monctonspca.ca
                        </p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="widget">
                        <h5>Visit Us</h5>
                        <ul class="link-list">
                            <li><b>Monday to Friday:</b> 10am to 7pm</li>
                            <li><b>Saturday and Sunday:</b> 12pm to 4pm</li>
                        </ul>
                        <br>
                        <ul class="social-network text-left">
                            <li><a href="#" data-toggle="tooltip" title="Find us on Facebook"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" data-toggle="tooltip" title="Follow us on Twitter"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" data-toggle="tooltip" title="Connect with us on Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#" data-toggle="tooltip" title="Find us on Instagram"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>

        <div id="sub-footer">
            <div class="copyright">
                <p>
                    <span>&copy;@DateTime.Now.Year - Greater Moncton SPCA</span>
                </p>
            </div>
        </div>
    </footer>
        

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @* brettdinelli: update to bootstrap 4 - requires popper.js *@
    @*<script src="~/lib/popper.js/dist/umd/popper.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    @*<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>*@
    <script src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"
            asp-fallback-src="~/lib/popper.js/dist/popper.min.js"
            asp-fallback-test="window.Popper">
    </script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    @*<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>*@
    <script src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>